Handle output closing in the middle of our write
When cpd.py produces more than about 4 KiB of output into a process
reading in a pipeline, and that process closes the pipeline, it used
to throw this for small overflows:

    close failed in file object destructor:
    sys.excepthook is missing
    lost sys.stderr

and this for large overflows:

    Traceback (most recent call last):
      File ".../cpd/bin/cpd.py", line 222, in <module> main()
      File ".../cpd/bin/cpd.py", line 218, in main sys.stdout.write(p)
    IOError: [Errno 32] Broken pipe

Answers to <https://stackoverflow.com/q/42722411/107294> helped here.